[features]
seeds = false
[programs.localnet]
musechain_escrow = "3tB4rGwEj3B8YjozEBTHL5f8Tzubq9kiYJP4E6nyKQDX"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/gbenga/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_time = 1000000
